# Generated by Django 3.2.5 on 2021-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='country',
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
