# Generated by Django 3.2.5 on 2021-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default='blog.png', null=True, upload_to='images/'),
        ),
    ]
