# Generated by Django 3.2.5 on 2021-07-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointmentlist_appointmentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='AppointmentList',
        ),
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
    ]
