# Generated by Django 3.2.5 on 2021-07-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
